### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by trashbirdecology** [beausoleilmo/Ornithometrics-ctv#1]
I suggest making the [Table of Contents for the package](https://beausoleilmo.github.io/Ornithometrics-ctv/Ornithometrics.html#toc) more obvious on the README page. Took me a hot minute to get to the package list, and I did this using a link you provided rather than the repository.

**Comment by beausoleilmo** [comment]
Thanks a lot for your suggestion! I modified it  👉 83dfd890ddb2e7a8aef6231a7c4b714e3dd841e2
